name: Cpp linter
permissions:
  pull-requests: write
on:
  push:
    branches: [ main, develop ]
  pull_request:
      branches: [ main, develop ]
      paths: ['**.c', '**.cpp', '**.h', '**.hpp', '**.cxx', '**.hxx', '**.cc', '**.hh', '**CMakeLists.txt', 'meson.build', '**.cmake']

jobs:
  style-linter:      
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Style Check
        uses: cpp-linter/cpp-linter-action@v2
        id: cppLinter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: 'file' # uses nearest .clang-format config file
          tidy-checks: '' # uses nearest .clang-tidy config file
          extra-args: '-std=c++17' #extra arguments to pass to clang-tidy, will use C++17 standard
          thread-comments: ${{ github.event_name == 'pull_request' && 'update' }}
      - name: Check Fail
        if: steps.cppLinter.outputs.checks-failed > 0
        run: exit 1
