name: Cpp linter
on:
  pull_request:
    branches: [ main, develop ]
    paths: [ '**.c', '**.cpp', '**.h', '**.hpp', '**.cxx', '**.hxx', '**.cc', '**.hh', '**CMakeLists.txt', 'meson.build', '**.cmake' ]
  push:
    branches: [ main, master, develop ]
    paths: [ '**.c', '**.cpp', '**.h', '**.hpp', '**.cxx', '**.hxx', '**.cc', '**.hh', '**CMakeLists.txt', 'meson.build', '**.cmake' ]
jobs:
  style-linter:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Style Check
        uses: cpp-linter/cpp-linter-action@v2
        id: cppLinter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: 'file:.clang-format_CI' # uses nearest .clang-format config file
          tidy-checks: '' # uses nearest .clang-tidy config file
          format-review: true
          tidy-review: true
          extra-args: '-std=c++17' #extra arguments to pass to clang-tidy, will use C++17 standard
          thread-comments: ${{ github.event_name == 'pull_request' && 'update' }}
      - name: Check Fail
        if: steps.cppLinter.outputs.checks-failed > 0
        run: exit 1
