name: CI

on:
  pull_request:
    types:
      - assigned
      - unassigned
      - opened
      - edited
      - reopened
      - converted_to_draft
      - ready_for_review
      - review_requested
      - review_request_
  workflow_dispatch:
permissions:
  pull-requests: write
jobs:
  assignee-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            let pr = context.payload.pull_request
            let assignees = pr.assignees
            let hasError = false
            let errorText = ""
            if(assignees == null || assignees.length == 0){
              core.error("No Assignee selected!")
              hasError = true
            }
            
            if(hasError){
              throw new Error("Unresolved Errors in PR!")
            }
  reviewer-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            let pr = context.payload.pull_request
            let hasError = false
            let errorText = ""

            let reviewers = pr.requested_reviewers
            if(reviewers == null || reviewers.length == 0){
              core.error("No Reviewers Assigned!")
              hasError = true;
            }

            let title = pr.title
            let reg = /^\[HTS-\d{3,}\]/
            let matches = title.match(reg)

            if(matches == null || matches.length == 0){
              core.error("Title should contain [HTS-XXXX] at the beginning!")
              hasError = true
            }
            
            if(hasError){
              throw new Error("Unresolved Errors in PR!")
            }
  regex-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            let pr = context.payload.pull_request
            let hasError = false
            let errorText = ""

            let title = pr.title
            let reg = /^\[HTS-\d{3,}\]/
            let matches = title.match(reg)

            if(matches == null || matches.length == 0){
              core.error("Title should contain [HTS-XXXX] at the beginning!")
              hasError = true
            }
            
            if(hasError){
              throw new Error("Unresolved Errors in PR!")
            }
    
  
          
        

        
        
