name: CI

on:
  pull_request:
    types:
      - opened
      - edited
      - labeled
      - unlabeled
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
permissions:
  pull-requests: write
jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            let assignee = context.payload.pull_request.assignee;
            if(assignee == null){
              throw new Error("Assignee Required");
            }
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.number }}
        
