name: CI

on:
  pull_request:
    types:
      - opened
      - edited
  workflow_dispatch:
permissions:
  pull-requests: write
jobs:
  pr-lint:
    runs-on: ubuntu-latest
    steps:
      - name: check assignee
        uses: actions/github-script@v7
        with:
          script: |
            let assignees = context.payload.pull_request.assignees
            if(assignees == null || assignees.length == 0){
              console.log("No assignee")
              return
            }
            console.log("assignee found")
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.number }}
        
