name: CI

on:
  pull_request:
    types:
      - assigned
      - unassigned
      - opened
      - edited
      - reopened
      - converted_to_draft
      - ready_for_review
      - review_requested
      - review_request_
  workflow_dispatch:
permissions:
  pull-requests: write
jobs:
  pr-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        id: linter
        with:
          result-encoding: string
          script: |
            let pr = context.payload.pull_request
            let assignees = pr.assignees
            let hasError = false
            let errorText = ""
            if(assignees == null || assignees.length == 0){
              errorText += "No Assignee! "
              hasError = true
            }
            let reviewers = pr.requested_reviewers
            if(reviewers == null || reviewers.length == 0){
              errorText += "No reviewers! "
              hasError = true
            }

            let title = pr.title
            let reg = /\[HTS-\d{3,}\]
            let matches = title.match(reg)

            if(matches == 0){
              errorText += "Title should have [HTS-XXXX]"
              hasError = true
            }
            
            if(hasError){
              core.setOutput("ERROR", errorText)
              core.error(errorText)
            }
      - name: outputError
        env:
          ERROR: ${{ steps.linter.outputs.ERROR }}
        run: echo $ERROR > $GITHUB_STEP_SUMMARY
        
          
        

        
        
