name: CI

on:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - run: gh pr edit "$NUMBER" -t "[HTS-XXXX]"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.number }}
